config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
	resources :paintings, :exhibitions, :museums
	root "paintings#index"
	delete 'delete_picture', to: 'paintings#delete_picture'
	get "search", to: 'paintings#search', as: :search
end

app/models/exhibition.rb
class Exhibition < ActiveRecord::Base
	has_and_belongs_to_many :paintings
	validates :year, presence: true
	
	belongs_to :museum, :class_name => 'Museum'
	validates :museum, presence: true
	
	def full_display
		return self.year.to_s+" - "+self.museum.full_display
	end
end

app/models/exhibitions_painting.rb
class ExhibitionsPainting < ActiveRecord::Base
	belongs_to :exhibition
	belongs_to :painting
end

app/models/museum.rb
class Museum < ActiveRecord::Base
	has_many :exhibitions
	has_many :paintings
	
	validates :name, presence: true
	validates :city, presence: true
	
	def full_display
		return self.name+" - "+self.city
	end
end

app/models/painting.rb
class Painting < ActiveRecord::Base
	validates :title, presence: true
	validates :number, presence: true, uniqueness: true

	validates :lemoisne, uniqueness: true

	has_attached_file :picture
	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
	before_destroy { |painting| painting.picture.destroy }
	
	validates :technique, presence: true
	validates_inclusion_of :technique, :in => ["Huile sur toile", "Huile sur papier", "Huile sur panneau", "Huile sur carton", "Huile sur autre", "Pastel sur papier", "Pastel sur autre", "Mixte sur toile", "Mixte sur papier", "Mixte sur autre", "Pastel et fusain"]
	
	validates :cachet, presence: true
	validates_inclusion_of :cachet, :in => ["Vente Degas", "Atelier", "Invisible", "Pas de cachet"]
	
	validates :localisation, presence: true
	validates_inclusion_of :localisation, :in => ["Musée", "Collection Particulière", "Inconnu"]

	validates :signature, presence: true
	validates_inclusion_of :signature, :in => ["Signé", "Non signé", "Invisible"]

	has_and_belongs_to_many :exhibitions
	accepts_nested_attributes_for :exhibitions
	
	validates_inclusion_of :has_accurate_date, :in => [true, false]
	
	validates :year, presence: true, if: :has_accurate_date
	validates_inclusion_of :circa, :in => [true, false], if: :has_accurate_date
	
	validates :period, presence: true, if: :not_has_accurate_date
	validates_inclusion_of :period, :in => ["1850-1860","1860-1870","1870-1880","1880-1890","1890-1900","1900-1910"], if: :not_has_accurate_date
	
	belongs_to :museum, :class_name => 'Museum'
	validates :museum, presence: true, if: :should_have_museum
	
	def not_has_accurate_date
		return !self.has_accurate_date if !has_accurate_date.nil?
		return false if has_accurate_date.nil?
	end
	
	def should_have_museum
		return self.localisation == "Musée"
	end

	def sort_date
		return (has_accurate_date) ? year : period.split("-")[0].to_i
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception


  def to_inchs(cms)
    inchs = cms/2.54
    return inchs.round(2)
    # multiple = 1
    # res = []
    # while multiple <= 64 do
    #     res.push((inchs/multiple).floor)
    #     multiple *= 2
    #     inchs -= (inchs/multiple).floor
    # end
    # puts "====>"+res.count.to_s
    # size = res.count
    # (0..(size-1)).each do |i|
    #   return res.slice!(7-i) and break if((res[6-i] != 0) && (res[7-i] == 0))
    # end 
  end

     before_filter :authenticate
  		protected
		    def authenticate
		      authenticate_or_request_with_http_basic do |username, password|
		      username == "michel" && password == "newyork"
		      username == "marie" && password == "losserand"
		    end
  		end
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
	def index
		@exhibitions = Exhibition.all
	end
	
	def new
		@exhibition = Exhibition.new()
	end
	
	def create
		@exhibition = Exhibition.new(exhibition_params)
		if @exhibition.save
			flash[:success] = "L'exposition a été correctement !"
			redirect_to @exhibition
		else
			render 'new'
		end
	end
	
	def show
		@exhibition = Exhibition.find(params[:id])
	end
	
	def edit
		@exhibition = Exhibition.find(params[:id])
	end
	
	def update
		@exhibition = Exhibition.find(params[:id])
		if @exhibition.update_attributes(exhibition_params)
			flash[:success] = "L'exposition a été correctement mise à jour!"
			redirect_to @exhibition
		else
			render 'edit'
		end
	end
	
	def destroy
		@exhibition = Exhibition.find(params[:id])
		@exhibition.destroy
		flash[:success] = "L'exposition a été détruite!"
		redirect_to exhibitions_path
	end
	
private
	def exhibition_params
    	params.require(:exhibition).permit(:year, :number, :remark, :museum_id)
	end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController

def index
		@museums = Museum.all
	end
	
	def new
		@museum = Museum.new()
	end
	
	def create
		@museum = Museum.new(museum_params)
		if @museum.save
			flash[:success] = "Le musée a été correctement créé !"
			redirect_to @museum
		else
			render 'new'
		end
	end
	
	def show
		@museum = Museum.find(params[:id])
	end
	
	def edit
		@museum = Museum.find(params[:id])
	end
	
	def update
		@museum = Museum.find(params[:id])
		if @museum.update_attributes(museum_params)
			flash[:success] = "Le musée a été correctement mis à jour "
			redirect_to @museum
		else
			render 'edit'
		end
	end
	
	def destroy
		@museum = Museum.find(params[:id])
		if !@museum.exhibitions.any? && !@museum.paintings.any?
			@museum.destroy
			flash[:success] = "La musée a été détruit!"
			redirect_to museums_path and return
		else
			flash[:warning] = "Ce musée est enregistré comme hébergeant des oeuvres ou ayant des expositions référencées. Vous ne pouvez pas le détruire!"
			redirect_to @museum and return
		end
	end
	
private
	def museum_params
    	params.require(:museum).permit(:name, :city, :remark)
	end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController

	def index
		@paintings = Painting.all.sort_by{|e| e.sort_date}
	end

	def search
		@paintings = [];
		@query = params[:q]

		Painting.all.each do |painting|
			@paintings << painting if painting.title.downcase.include?(params[:q].downcase) || painting.carton.downcase.include?(params[:q].downcase) || painting.description.downcase.include?(params[:q].downcase)
		end
		@paintings = @paintings.sort_by{|e| e.sort_date}
	end
	
	def new
		number = Painting.count !=0 ? Painting.all.collect{|p| p.number.to_i}.max + 1 : 1
		@painting = Painting.new(number: number)
	end
	
	def create
		@painting = Painting.new(painting_params)
		if @painting.has_accurate_date
			@painting.period = nil
		else
			@painting.circa = nil 
			@painting.year = nil
		end
		if @painting.save
			flash[:success] = "La fiche a été correctement crée!"
			redirect_to @painting
		else
			render 'new'
		end
	end
	
	def show
		@painting = Painting.find(params[:id])
		@heigth_inch = to_inchs(@painting.heigth)
		@width_inch = to_inchs(@painting.width)
	end
	
	def edit
		@painting = Painting.find(params[:id])
	end
	
	def update
		@painting = Painting.find(params[:id])
		opened_params = painting_params
		if opened_params[:has_accurate_date] == "true"
			opened_params[:period] = nil
		else
			opened_params[:circa] = nil
			opened_params[:year] = nil 
		end
		if @painting.update_attributes(opened_params)
			flash[:success] = "La fiche a été correctement mise à jour!"
			redirect_to @painting
		else
			render 'edit'
		end
	end
	
	def destroy
		@painting = Painting.find(params[:id])
		@painting.destroy
		flash[:success] = "La fiche a été détruite!"
		redirect_to paintings_path
	end

	def delete_picture
		@painting = Painting.find(params[:id_painting])
		if @painting.picture.destroy
			@painting.update_attributes(picture: nil)
		flash[:success] = "La photo a été détruite!"
		else
		end
		redirect_to edit_painting_path(@painting)
	end

private
	def painting_params
    	params.require(:painting).permit(:heigth, :width, :unit, :signature, :carton, :lemoisne, :description, :title, :picture, :localisation, :number, :technique, :cachet, :has_accurate_date, :year, :circa, :period, :museum_id, exhibition_ids: [])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/helpers/museum_helper.rb
module MuseumHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/exhibitions/_show.html.erb
<%= link_to "#{exhibition.museum.full_display} (#{exhibition.year})", exhibition %> 

app/views/exhibitions/edit.html.erb
<% provide(:title, "Modification d'un exposition") %>
<h2>Modification d'un exposition...</h2>

<%= form_for @exhibition do |f| %>

		<% if @exhibition.errors.any? %>
			<%= pluralize(@exhibition.errors.count, "error") %> prohibited this exhibition from being created:
			<ul>
				<% @exhibition.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		<% end %>
		
		
		<div class="field form-group">
			<%= f.label(:museum_id, "Musée de l'exposition", class: "col-md-4 control-label" ) %>	
			<div class="col-sm-8"><%= f.collection_select(:museum_id, Museum.all, :id, :full_display, {prompt: "Sélectionner le musée..."}, {class: "form-control"})  %></div>
		</div>
		<br/><br/>
		
		<div class="field form-group">
			<%= f.label(:year, "Date de l'exposition", class: "col-sm-4 control-label"  ) %>	
			<div class="col-sm-8"><%= f.select :year, (1860..2016), {prompt: "Date de l'oeuvre..."}, {class: "form-control"}  %></div>
		</div>	
		<br/><br/>	

		<div class="field form-group">
			<%= f.label(:number, "Numéro de l'expo si nécessaire (plusieurs expos dans la même musée sur cette année ou période)", class: "col-sm-4 control-label"  ) %>	
			<div class="col-sm-8">			
				<%= f.number_field :number, class: "form-control"%>
			</div >
		</div>
		<br/><br/>

		<div class="field form-group">
			<%= f.label(:remark, "Remarques ou nom de l'expo", class: "col-sm-4 control-label") %>
			<div class="col-sm-8">		
				<%= f.text_field :remark, class: "form-control" %>
			</div >
		</div >
		<br/><br/>
		

	<%= f.submit "Modifier l'expo" %>
<% end %>


<%= link_to "Abandonner l'édition de cette expo", url_for(action: 'show', id: @exhibition)%><br/>


app/views/exhibitions/index.html.erb
<% provide(:title, "Toutes les expositions") %>
<h2>Voici toutes les expositions...</h2>
<ul>
	<% @exhibitions.each do |exhibition| %>
		<li>
			<%= render 'exhibitions/show', :exhibition => exhibition %> 
		</li>
	<% end %>
</ul>


app/views/exhibitions/new.html.erb
<% provide(:title, "Nouvelle Exposition") %>
<div class="page-header">
<h2>Création d'une nouvelle expo...</h2>
</div>

<%= form_for @exhibition do |f| %>

		<% if @exhibition.errors.any? %>
			<%= pluralize(@exhibition.errors.count, "error") %> prohibited this exhibition from being created:
			<ul>
				<% @exhibition.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		<% end %>
		
		<div class="field form-group">
			<%= f.label(:museum_id, "Musée de l'exposition", class: "col-md-4 control-label" ) %>	
			<div class="col-sm-8"><%= f.collection_select(:museum_id, Museum.all, :id, :full_display, {prompt: "Sélectionner le musée..."}, {class: "form-control"})  %></div>
		</div>
		<br/><br/>
		
		<div class="field form-group">
			<%= f.label(:year, "Date de l'exposition", class: "col-sm-4 control-label"  ) %>	
			<div class="col-sm-8"><%= f.select :year, (1860..2016), {prompt: "Date de l'expo..."}, {class: "form-control"}  %></div>
		</div>	
		<br/><br/>	

		<div class="field form-group">
			<%= f.label(:number, "Numéro de l'expo si nécessaire (plusieurs expos dans la même musée sur cette année ou période)", class: "col-sm-4 control-label"  ) %>	
			<div class="col-sm-8">			
				<%= f.number_field :number, class: "form-control"%>
			</div >
		</div>
		<br/><br/>

		<div class="field form-group">
			<%= f.label(:remark, "Remarques ou nom de l'expo", class: "col-sm-4 control-label") %>
			<div class="col-sm-8">		
				<%= f.text_field :remark, class: "form-control" %>
			</div >
		</div >
		<br/><br/>
		

	<%= f.submit "Créer l'expo", class: "btn btn-primary" %>
<% end %>


app/views/exhibitions/show.html.erb
<% provide(:title, "Expo") %>
<div class="page-header">
<h2><%= @exhibition.museum.full_display %>(<%= @exhibition.year%>)</h2>
</div>

<% if !@exhibition.number.nil? %>Exposition numéro <%= @exhibition.number.to_s %><br/><% end %>
<% if !@exhibition.remark.nil? %>Remarques sur l'expo : <%= @exhibition.remark.to_s %><br/><% end %>

<% if @exhibition.paintings.any? %>
Liste des oeuvres exposées dans cette expo : 
	<ul>
		<% @exhibition.paintings.each do |painting| %>
			<li><%= render 'paintings/show', :painting => painting %> </li>
		<% end %>
	</ul>
<% end %>

<%= link_to "Modifier l'expo ci-dessus", url_for(action: 'edit', id: @exhibition),  class: "btn btn-link"%><br/>
<%= button_to "Détruire l'expo ci-dessus", {action: 'destroy', id: @exhibition}, method: :delete, data: { confirm: "Are you sure?" },  class: "btn btn-link" %><br/>



app/views/layouts/_header.html.erb
<head>
  <title><%= yield(:title) %> | Degas </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
		<ul class="nav nav-tabs">
		    <li role="presentation" ><%= link_to "Toutes les fiches", root_path %></li>
			<li role="presentation" ><%= link_to "Créer une fiche", new_painting_path %></li>
			<li role="presentation" ><%= link_to "Toutes les expos", exhibitions_path %></li>
			<li role="presentation" ><%= link_to "Créer une expo", new_exhibition_path %></li>
		    <li role="presentation" ><%= link_to "Tous les musées", museums_path %></li>
			<li role="presentation" ><%= link_to "Créer un musée", new_museum_path %></li>
		
			<li role="presentation" >
				<%= form_tag(search_path, {method: :get, class: "navbar-form navbar-right" } ) do %>
					<div class="form-group">
  						<%= text_field_tag(:q, nil, class: "form-control", placeholder: "Search" ) %>
 					</div>
  					<%= submit_tag("Chercher une fiche", class: "btn btn-default") %>
				<% end %>
      		</li>
      	</ul>
   </div>
  </div>
</nav>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<%= render 'layouts/header' %>
	<body>
		<%= render 'layouts/navbar' %>
	    <% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>

		<%= yield %>
	</body>
</html>

app/views/museums/_show.html.erb
<%= link_to museum.full_display, museum %> 




app/views/museums/edit.html.erb
<% provide(:title, "Edition d'un musée") %>
<h2>Edition d'un musée...</h2>

<%= form_for @museum do |f| %>

		<% if @museum.errors.any? %>
			<%= pluralize(@museum.errors.count, "error") %> prohibited this museum from being created:
			<ul>
				<% @museum.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		<% end %>
		
		<div class="field form-group">
			<%= f.label(:name, "Nom du musée", class: "col-sm-4 control-label") %>
			<div class="col-sm-8">		
				<%= f.text_field :name, class: "form-control" %>
			</div >
		</div >
		<br/><br/>

		<div class="field form-group">
			<%= f.label(:city, "Ville du musée", class: "col-sm-4 control-label") %>
			<div class="col-sm-8">		
				<%= f.text_field :city, class: "form-control" %>
			</div >
		</div >
		<br/><br/>
		
		<div class="field form-group">
			<%= f.label(:remark, "Remarque éventuelle", class: "col-sm-4 control-label") %>
			<div class="col-sm-8">		
				<%= f.text_field :remark, class: "form-control" %>
			</div >
		</div >
		<br/><br/>

	<%= f.submit "Modifier le musée", class: "btn btn-primary" %>
<% end %>

<%= link_to "Abandonner l'édition de ce musée", url_for(action: 'show', id: @museum)%><br/>


app/views/museums/index.html.erb
<% provide(:title, "Tous les musées") %>
<h2>Voici tous les musées...</h2>
<ul>
	<% @museums.each do |museum| %>
		<li>
			<%= render 'show', :museum => museum %> 
		</li>
	<% end %>
</ul>


app/views/museums/new.html.erb
<% provide(:title, "Nouveau musée") %>
<div class="page-header">
<h2>Création du'un nouveau musée</h2>
</div>

<%= form_for @museum do |f| %>

		<% if @museum.errors.any? %>
			<%= pluralize(@museum.errors.count, "error") %> prohibited this museum from being created:
			<ul>
				<% @museum.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		<% end %>

		<div class="field form-group">
			<%= f.label(:name, "Nom du musée", class: "col-sm-4 control-label") %>
			<div class="col-sm-8">		
				<%= f.text_field :name, class: "form-control" %>
			</div >
		</div >
		<br/><br/>

		<div class="field form-group">
			<%= f.label(:city, "Ville du musée", class: "col-sm-4 control-label") %>
			<div class="col-sm-8">		
				<%= f.text_field :city, class: "form-control" %>
			</div >
		</div >
		<br/><br/>
		
		<div class="field form-group">
			<%= f.label(:remark, "Remarque éventuelle", class: "col-sm-4 control-label") %>
			<div class="col-sm-8">		
				<%= f.text_field :remark, class: "form-control" %>
			</div >
		</div >
		<br/><br/>

	<%= f.submit "Créer le musée", class: "btn btn-primary" %>
<% end %>


app/views/museums/show.html.erb
<% provide(:title, "Musée") %>
<h2>Voici le musée...</h2><br/>

Nom du musée : <%= @museum.name %><br/>
Ville du musée : <%= @museum.city %><br/>
<% !@museum.remark.nil? ? "Remarque :  "+@museum.remark : "" %><br/>

<% if @museum.exhibitions.any? %>
Liste des expositons que ce musée a hébergée : 
	<ul>
		<% @museum.exhibitions.sort_by{|e| e.year}.each do |exhibition| %>
			<li><%= render 'exhibitions/show', :exhibition => exhibition %> </li>
		<% end %>
	</ul>
<% end %>

<% if @museum.paintings.any? %>
Liste des oeuvres que ce musée héberge : 
	<ul>
		<% @museum.paintings.sort_by{|e| e.sort_date}.each do |painting| %>
			<li><%= render 'paintings/show', :painting => painting %> </li>
		<% end %>
	</ul>
<% end %>

<%= link_to "Modifier le musée ci-dessus", url_for(action: 'edit', id: @museum), class: "btn btn-link"%><br/>
<%= button_to "Détruire le musée ci-dessus", {action: 'destroy', id: @museum}, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %><br/>



app/views/paintings/_show.html.erb
<%= link_to painting.title.to_s, painting %> (<%= painting.has_accurate_date ? (painting.circa ? "Circa "+painting.year.to_s : painting.year.to_s ) : (painting.period.to_s) %>)<br/>




app/views/paintings/edit.html.erb
<% provide(:title, "Edition d'une fiche") %>
<h2>Edition d'une fiche...</h2>

<% if @painting.picture.present? %>
	<%= image_tag @painting.picture.url, height: '320' %>
	<%= button_to "Détruire cette photo", { controller: 'paintings', action: 'delete_picture'}, params: {id_painting: @painting.id}, method: :delete, data: { confirm: "Are you sure?" } %><br/>
<% end %>	

<%= form_for @painting do |f| %>

		<% if @painting.errors.any? %>
			<%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being created:
			<ul>
				<% @painting.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		<% end %>
		
			<div class="field form-group">
				<%= f.label(:title, "Titre de l'oeuvre", class: "col-sm-4 control-label") %>
				<div class="col-sm-8">		
					<%= f.text_field :title, class: "form-control" %>
				</div >
			</div >
			<br/><br/>

			<div class="field form-group">
				<%= f.label(:carton, "Carton", class: "col-sm-4 control-label") %>
				<div class="col-sm-8">		
					<%= f.bootsy_area :carton, editor_options: { image: false, link: false, color: false}, class: "form-control", rows: "8"%>
				</div >
			</div >
			<br/><br/>

			<div class="field form-group">
				<%= f.label(:description, "Description", class: "col-sm-4 control-label") %>
				<div class="col-sm-8">		
					<%= f.bootsy_area :description, editor_options: { image: false, link: false, color: false}, class: "form-control", rows: "8" %>
				</div >
			</div >
			<br/><br/>

			<% if !@painting.picture.present? %>
	 			<div class="field">
	    			<%= f.label(:picture,  "Dessin à uploader", class: "col-sm-4 control-label") %>
	    			<%= f.file_field :picture %>
	  			</div>
				<br/><br/>
			<% end %>


			<div class="field form-group">
				<%= f.label(:number, "Numéro de l'oeuvre (référence interne Word)", class: "col-sm-4 control-label"  ) %>	
				<div class="col-sm-8">			
					<%= f.number_field :number, class: "form-control"%>
				</div >
			</div>
			<br/><br/>

			<div class="field form-group">
				<%= f.label(:lemoisne, "Numéro Lemoisne (éventuel)", class: "col-sm-4 control-label"  ) %>	
				<div class="col-sm-8">			
					<%= f.number_field :lemoisne, class: "form-control"%>
				</div >
			</div>
			<br/><br/>


			<div class="field form-group">
				<%= f.label(:has_accurate_date, "Datation de l'oeuvre :", class: "col-sm-4 control-label"  ) %>
	 			<div class="col-sm-8" data-toggle="buttons">
					<%= f.label(:has_accurate_date, "Date précise"  ) do %>	
						<%= f.radio_button :has_accurate_date, 'true' %> Année
					<% end %>
					<%= f.label(:has_accurate_date, "Période" ) do %>	
						<%= f.radio_button :has_accurate_date, 'false' %> Période
					<% end %>
	  			</div>
			</div>
			<br/><br/>


				<div class="field form-group">
					<%= f.label(:circa, "Si datation sur une année :", class: "col-sm-4 control-label"  ) %>
		 			<div class="col-sm-8" data-toggle="buttons">
						<%= f.label(:circa, "Date précise"  ) do %>	
							<%= f.radio_button :circa, 'true' %> Année circa
						<% end %>
						<%= f.label(:circa, "Période" ) do %>	
							<%= f.radio_button :circa, 'false' %> Année précise
						<% end %>
		  			</div>
				</div>
				<br/><br/>
				
				<div class="field form-group">
					<%= f.label(:year, "Date de l'oeuvre", class: "col-sm-4 control-label"  ) %>	
					<div class="col-sm-8"><%= f.select :year, (1860..1900), {prompt: "Date de l'oeuvre..."}, {class: "form-control"}  %></div>
				</div>	
				<br/><br/>	

				<div class="field form-group">
					<%= f.label(:period, "Période de l'oeuvre", class: "col-md-4 control-label"  ) %>	
					<div class="col-sm-8"><%= f.select :period, ["1850-1860","1860-1870","1870-1880","1880-1890","1890-1900","1900-1910"], {prompt: "Période de l'oeuvre..."}, {class: "form-control"}%></div>
				</div>
				<br/><br/>
				
				<div class="field form-group">
					<%= f.label(:technique, "Technique et support de l'oeuvre", class: "col-md-4 control-label"  ) %>	
					<div class="col-sm-8"><%= f.select :technique,["Huile sur toile", "Huile sur papier", "Huile sur panneau", "Huile sur carton", "Huile sur autre", "Pastel sur papier", "Pastel sur autre", "Mixte sur toile", "Mixte sur papier", "Mixte sur autre", "Pastel et fusain"] \
				, {prompt: "Technique et support de l'oeuvre..."}, {class: "form-control"} %> </div>
				</div>
				<br/><br/>


			<div class="field form-group">
				<%= f.label(:cachet, "Cachet", class: "col-md-4 control-label" ) %>	
				<div class="col-sm-8"><%= f.select :cachet, ["Vente Degas", "Atelier", "Invisible"] , {prompt: "Cachet..."}, {class: "form-control"}  %></div> 
			</div>
			<br/><br/>

			<div class="field form-group">
				<%= f.label(:signature, "Signature", class: "col-md-4 control-label" ) %>	
				<div class="col-sm-8"><%= f.select :signature, ["Signé", "Non signé", "Invisible"] , {prompt: "Signature..."}, {class: "form-control"}  %></div> 
			</div>
			<br/><br/>

			<div class="field form-group">
				<%= f.label(:localisation, "Localisation", class: "col-md-4 control-label" ) %>	
				<div class="col-sm-8"><%= f.select :localisation, ["Musée", "Collection Particulière", "Inconnu"], {prompt: "Localisation..."}, {class: "form-control"} %> </div>
			</div>
			<br/><br/>

			<div class="field form-group">
				<%= f.label(:museum_id, "Musée actuel", class: "col-md-4 control-label" ) %>	
				<div class="col-sm-8"><%= f.collection_select(:museum_id, Museum.all, :id, :full_display, {prompt: "Sélectionner le musée..."}, {class: "form-control"})  %></div>
			</div>
			<br/><br/>

			<div class="field form-group">
				<%= f.label(:museum_id, "Expositions de l'oeuvre (Choix multiple possible)", class: "col-md-4 control-label" ) %>	
				<div class="col-sm-8"><%= f.collection_select(:exhibition_ids, Exhibition.all, :id, :full_display, {}, {multiple: true, class: "form-control"})  %> </div>
			</div>

			<div class="field form-group">
				<%= f.label(:heigth, "Hauteur en Cms", class: "col-sm-4 control-label"  ) %>	
				<div class="col-sm-8">			
					<%= f.number_field :heigth, class: "form-control"%>
				</div >
			</div>

			<div class="field form-group">
				<%= f.label(:width, "Largeur en Cms", class: "col-sm-4 control-label"  ) %>	
				<div class="col-sm-8">			
					<%= f.number_field :width, class: "form-control"%>
				</div >
			</div>

	<%= f.submit "Mettre à jour la fiche", class: "btn btn-default" %>
<% end %>

<%= link_to "Abandonner l'édition de cette fiche", url_for(action: 'show', id: @painting)%><br/>
